version: '3.7'

services:
  database:
    image: postgres:15.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret123
    ports:
      - "35432:5432"
    volumes:
      - "pg_data:/var/lib/postgresql/data/"
  app:
    image: ghcr.io/micky5991/clips:dev
    build:
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:secret123@database:5432/postgres"
    links:
      - database
    volumes:
      - "./prisma/data/:/app/prisma/data/"

volumes:
  pg_data:
